server:
  port: 8007

spring:
  kafka:
    template:
      default-topic: transaction-events
    producer:
      bootstrap-server: kafka-aforo255:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://postgres-aforo255:5432/db_account
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
  redis:
    host: redis-aforo255
    port: 6379


logging:
  level:
    root: INFO
    com.aforo255.deposit: INFO
    org.hibernate.sql: DEBUG


topic:
  name: transaction-events
